server:
  port: 8080
  servlet:
    session:
      timeout: 30m
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  ## redirection http 현상 제거 ##
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

logging:
  config: classpath:logback.xml

spring:
  application:
    name: NANURI IT Corp In-house System 
  datasource:
    url: jdbc:log4jdbc:mysql://172.30.1.32:3306/work?serverTimezone=Asia/Seoul
    username: work
    password: Nanuriwork1!
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      port: 35729

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
        jdbc:
          batch_size: 100
          time_zone: Asia/Seoul
    generate-ddl: false
    hibernate:
      ddl-auto: none